-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS newstart_db.constraint_profiles
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    unit_id uuid NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    max_consecutive_work_days integer,
    max_consecutive_night_shifts integer,
    min_rest_hours_between_shifts integer,
    fairness_weight_json jsonb,
    penalty_weight_json jsonb,
    attributes jsonb DEFAULT '{}'::jsonb,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT constraint_profiles_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS newstart_db.coverage_rules
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    unit_id uuid NOT NULL,
    shift_code text COLLATE pg_catalog."default" NOT NULL,
    day_type text COLLATE pg_catalog."default" NOT NULL,
    min_workers integer NOT NULL,
    max_workers integer,
    required_tag text COLLATE pg_catalog."default",
    attributes jsonb DEFAULT '{}'::jsonb,
    CONSTRAINT coverage_rules_pkey PRIMARY KEY (id),
    CONSTRAINT coverage_rules_unit_id_shift_code_day_type_required_tag_key UNIQUE (unit_id, shift_code, day_type, required_tag)
);

CREATE TABLE IF NOT EXISTS newstart_db.external_messages
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    organization_id uuid NOT NULL,
    provider text COLLATE pg_catalog."default" NOT NULL,
    external_id text COLLATE pg_catalog."default" NOT NULL,
    worker_id uuid,
    direction text COLLATE pg_catalog."default" NOT NULL,
    message_id text COLLATE pg_catalog."default",
    text text COLLATE pg_catalog."default",
    detected_intent text COLLATE pg_catalog."default",
    payload_json jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT external_messages_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS newstart_db.organizations
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    name text COLLATE pg_catalog."default" NOT NULL,
    code text COLLATE pg_catalog."default" NOT NULL,
    timezone text COLLATE pg_catalog."default" NOT NULL DEFAULT 'Asia/Bangkok'::text,
    attributes jsonb DEFAULT '{}'::jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT organizations_pkey PRIMARY KEY (id),
    CONSTRAINT organizations_code_key UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS newstart_db.roles
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    code text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    CONSTRAINT roles_pkey PRIMARY KEY (id),
    CONSTRAINT roles_code_key UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS newstart_db.schedule_assignments
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    schedule_id uuid NOT NULL,
    worker_id uuid NOT NULL,
    date date NOT NULL,
    shift_code text COLLATE pg_catalog."default" NOT NULL,
    source text COLLATE pg_catalog."default" NOT NULL,
    attributes jsonb DEFAULT '{}'::jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT schedule_assignments_pkey PRIMARY KEY (id),
    CONSTRAINT schedule_assignments_schedule_id_worker_id_date_key UNIQUE (schedule_id, worker_id, date)
);

CREATE TABLE IF NOT EXISTS newstart_db.schedules
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    organization_id uuid NOT NULL,
    unit_id uuid NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    status newstart_db.schedule_status NOT NULL DEFAULT 'DRAFT'::newstart_db.schedule_status,
    constraint_profile_id uuid,
    last_solver_run_id uuid,
    created_by uuid NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    published_at timestamp with time zone,
    published_by uuid,
    attributes jsonb DEFAULT '{}'::jsonb,
    CONSTRAINT schedules_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS newstart_db.shift_templates
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    organization_id uuid NOT NULL,
    unit_id uuid,
    code text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    start_time time without time zone NOT NULL,
    end_time time without time zone NOT NULL,
    attributes jsonb DEFAULT '{}'::jsonb,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT shift_templates_pkey PRIMARY KEY (id),
    CONSTRAINT shift_templates_organization_id_unit_id_code_key UNIQUE (organization_id, unit_id, code)
);

CREATE TABLE IF NOT EXISTS newstart_db.sites
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    organization_id uuid NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    code text COLLATE pg_catalog."default" NOT NULL,
    address text COLLATE pg_catalog."default",
    timezone text COLLATE pg_catalog."default",
    attributes jsonb DEFAULT '{}'::jsonb,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT sites_pkey PRIMARY KEY (id),
    CONSTRAINT sites_organization_id_code_key UNIQUE (organization_id, code)
);

CREATE TABLE IF NOT EXISTS newstart_db.solver_run_assignments
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    solver_run_id uuid NOT NULL,
    worker_id uuid NOT NULL,
    date date NOT NULL,
    shift_code text COLLATE pg_catalog."default" NOT NULL,
    attributes jsonb DEFAULT '{}'::jsonb,
    CONSTRAINT solver_run_assignments_pkey PRIMARY KEY (id),
    CONSTRAINT solver_run_assignments_solver_run_id_worker_id_date_key UNIQUE (solver_run_id, worker_id, date)
);

CREATE TABLE IF NOT EXISTS newstart_db.solver_runs
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    schedule_id uuid NOT NULL,
    plan newstart_db.solver_plan NOT NULL,
    status newstart_db.solver_run_status NOT NULL DEFAULT 'QUEUED'::newstart_db.solver_run_status,
    requested_by uuid NOT NULL,
    notes text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    started_at timestamp with time zone,
    finished_at timestamp with time zone,
    failure_reason text COLLATE pg_catalog."default",
    kpis_json jsonb,
    objective_value numeric(12, 4),
    attributes jsonb DEFAULT '{}'::jsonb,
    CONSTRAINT solver_runs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS newstart_db.unit_memberships
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    unit_id uuid NOT NULL,
    user_id uuid NOT NULL,
    role_code text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT unit_memberships_pkey PRIMARY KEY (id),
    CONSTRAINT unit_memberships_unit_id_user_id_key UNIQUE (unit_id, user_id)
);

CREATE TABLE IF NOT EXISTS newstart_db.units
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    organization_id uuid NOT NULL,
    site_id uuid,
    name text COLLATE pg_catalog."default" NOT NULL,
    code text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    attributes jsonb DEFAULT '{}'::jsonb,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT units_pkey PRIMARY KEY (id),
    CONSTRAINT units_organization_id_code_key UNIQUE (organization_id, code)
);

CREATE TABLE IF NOT EXISTS newstart_db.user_roles
(
    user_id uuid NOT NULL,
    role_id uuid NOT NULL,
    CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_id)
);

CREATE TABLE IF NOT EXISTS newstart_db.users
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    organization_id uuid NOT NULL,
    email text COLLATE pg_catalog."default" NOT NULL,
    password_hash text COLLATE pg_catalog."default" NOT NULL,
    full_name text COLLATE pg_catalog."default" NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    attributes jsonb DEFAULT '{}'::jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS newstart_db.worker_availability
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    worker_id uuid NOT NULL,
    unit_id uuid NOT NULL,
    date date NOT NULL,
    shift_code text COLLATE pg_catalog."default" NOT NULL,
    type newstart_db.availability_type NOT NULL,
    source text COLLATE pg_catalog."default" NOT NULL,
    reason text COLLATE pg_catalog."default",
    attributes jsonb DEFAULT '{}'::jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT worker_availability_pkey PRIMARY KEY (id),
    CONSTRAINT worker_availability_worker_id_unit_id_date_shift_code_key UNIQUE (worker_id, unit_id, date, shift_code)
);

CREATE TABLE IF NOT EXISTS newstart_db.worker_external_ids
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    worker_id uuid NOT NULL,
    provider text COLLATE pg_catalog."default" NOT NULL,
    external_id text COLLATE pg_catalog."default" NOT NULL,
    attributes jsonb DEFAULT '{}'::jsonb,
    CONSTRAINT worker_external_ids_pkey PRIMARY KEY (id),
    CONSTRAINT worker_external_ids_provider_external_id_key UNIQUE (provider, external_id)
);

CREATE TABLE IF NOT EXISTS newstart_db.worker_preferences
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    worker_id uuid NOT NULL,
    prefers_day_shifts boolean,
    prefers_night_shifts boolean,
    max_consecutive_work_days integer,
    max_consecutive_night_shifts integer,
    preference_pattern_json jsonb,
    attributes jsonb DEFAULT '{}'::jsonb,
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT worker_preferences_pkey PRIMARY KEY (id),
    CONSTRAINT worker_preferences_worker_id_key UNIQUE (worker_id)
);

CREATE TABLE IF NOT EXISTS newstart_db.worker_unit_memberships
(
    worker_id uuid NOT NULL,
    unit_id uuid NOT NULL,
    role_code text COLLATE pg_catalog."default",
    CONSTRAINT worker_unit_memberships_pkey PRIMARY KEY (worker_id, unit_id)
);

CREATE TABLE IF NOT EXISTS newstart_db.workers
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    organization_id uuid NOT NULL,
    primary_unit_id uuid,
    full_name text COLLATE pg_catalog."default" NOT NULL,
    worker_code text COLLATE pg_catalog."default",
    employment_type newstart_db.employment_type,
    weekly_hours integer,
    attributes jsonb DEFAULT '{}'::jsonb,
    is_active boolean NOT NULL DEFAULT true,
    linked_user_id uuid,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT workers_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS newstart_db.constraint_profiles
    ADD CONSTRAINT constraint_profiles_unit_id_fkey FOREIGN KEY (unit_id)
    REFERENCES newstart_db.units (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS newstart_db.coverage_rules
    ADD CONSTRAINT coverage_rules_unit_id_fkey FOREIGN KEY (unit_id)
    REFERENCES newstart_db.units (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS newstart_db.external_messages
    ADD CONSTRAINT external_messages_organization_id_fkey FOREIGN KEY (organization_id)
    REFERENCES newstart_db.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS newstart_db.external_messages
    ADD CONSTRAINT external_messages_worker_id_fkey FOREIGN KEY (worker_id)
    REFERENCES newstart_db.workers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS newstart_db.schedule_assignments
    ADD CONSTRAINT schedule_assignments_schedule_id_fkey FOREIGN KEY (schedule_id)
    REFERENCES newstart_db.schedules (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS newstart_db.schedule_assignments
    ADD CONSTRAINT schedule_assignments_worker_id_fkey FOREIGN KEY (worker_id)
    REFERENCES newstart_db.workers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS newstart_db.schedules
    ADD CONSTRAINT schedules_constraint_profile_id_fkey FOREIGN KEY (constraint_profile_id)
    REFERENCES newstart_db.constraint_profiles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS newstart_db.schedules
    ADD CONSTRAINT schedules_created_by_fkey FOREIGN KEY (created_by)
    REFERENCES newstart_db.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS newstart_db.schedules
    ADD CONSTRAINT schedules_organization_id_fkey FOREIGN KEY (organization_id)
    REFERENCES newstart_db.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS newstart_db.schedules
    ADD CONSTRAINT schedules_published_by_fkey FOREIGN KEY (published_by)
    REFERENCES newstart_db.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS newstart_db.schedules
    ADD CONSTRAINT schedules_unit_id_fkey FOREIGN KEY (unit_id)
    REFERENCES newstart_db.units (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS newstart_db.shift_templates
    ADD CONSTRAINT shift_templates_organization_id_fkey FOREIGN KEY (organization_id)
    REFERENCES newstart_db.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS newstart_db.shift_templates
    ADD CONSTRAINT shift_templates_unit_id_fkey FOREIGN KEY (unit_id)
    REFERENCES newstart_db.units (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS newstart_db.sites
    ADD CONSTRAINT sites_organization_id_fkey FOREIGN KEY (organization_id)
    REFERENCES newstart_db.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS newstart_db.solver_run_assignments
    ADD CONSTRAINT solver_run_assignments_solver_run_id_fkey FOREIGN KEY (solver_run_id)
    REFERENCES newstart_db.solver_runs (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS newstart_db.solver_run_assignments
    ADD CONSTRAINT solver_run_assignments_worker_id_fkey FOREIGN KEY (worker_id)
    REFERENCES newstart_db.workers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS newstart_db.solver_runs
    ADD CONSTRAINT solver_runs_requested_by_fkey FOREIGN KEY (requested_by)
    REFERENCES newstart_db.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS newstart_db.solver_runs
    ADD CONSTRAINT solver_runs_schedule_id_fkey FOREIGN KEY (schedule_id)
    REFERENCES newstart_db.schedules (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS newstart_db.unit_memberships
    ADD CONSTRAINT unit_memberships_unit_id_fkey FOREIGN KEY (unit_id)
    REFERENCES newstart_db.units (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS newstart_db.unit_memberships
    ADD CONSTRAINT unit_memberships_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES newstart_db.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS newstart_db.units
    ADD CONSTRAINT units_organization_id_fkey FOREIGN KEY (organization_id)
    REFERENCES newstart_db.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS newstart_db.units
    ADD CONSTRAINT units_site_id_fkey FOREIGN KEY (site_id)
    REFERENCES newstart_db.sites (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS newstart_db.user_roles
    ADD CONSTRAINT user_roles_role_id_fkey FOREIGN KEY (role_id)
    REFERENCES newstart_db.roles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS newstart_db.user_roles
    ADD CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES newstart_db.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS newstart_db.users
    ADD CONSTRAINT users_organization_id_fkey FOREIGN KEY (organization_id)
    REFERENCES newstart_db.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS newstart_db.worker_availability
    ADD CONSTRAINT worker_availability_unit_id_fkey FOREIGN KEY (unit_id)
    REFERENCES newstart_db.units (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS newstart_db.worker_availability
    ADD CONSTRAINT worker_availability_worker_id_fkey FOREIGN KEY (worker_id)
    REFERENCES newstart_db.workers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS newstart_db.worker_external_ids
    ADD CONSTRAINT worker_external_ids_worker_id_fkey FOREIGN KEY (worker_id)
    REFERENCES newstart_db.workers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS newstart_db.worker_preferences
    ADD CONSTRAINT worker_preferences_worker_id_fkey FOREIGN KEY (worker_id)
    REFERENCES newstart_db.workers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS worker_preferences_worker_id_key
    ON newstart_db.worker_preferences(worker_id);


ALTER TABLE IF EXISTS newstart_db.worker_unit_memberships
    ADD CONSTRAINT worker_unit_memberships_unit_id_fkey FOREIGN KEY (unit_id)
    REFERENCES newstart_db.units (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS newstart_db.worker_unit_memberships
    ADD CONSTRAINT worker_unit_memberships_worker_id_fkey FOREIGN KEY (worker_id)
    REFERENCES newstart_db.workers (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS newstart_db.workers
    ADD CONSTRAINT workers_linked_user_id_fkey FOREIGN KEY (linked_user_id)
    REFERENCES newstart_db.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS newstart_db.workers
    ADD CONSTRAINT workers_organization_id_fkey FOREIGN KEY (organization_id)
    REFERENCES newstart_db.organizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS newstart_db.workers
    ADD CONSTRAINT workers_primary_unit_id_fkey FOREIGN KEY (primary_unit_id)
    REFERENCES newstart_db.units (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;